[package]
name = "Waves"
version = "0.1.0"
edition = "2024"

[dependencies]
cpal = "0.16.0"
eframe = "0.32.0"
egui_plot = "0.33.0"
num-complex = "0.4.6"
rand = "0.9.2"
symphonia = {version ="0.5.4", features = ["mp3"]}

